runtime: nodejs22
env: standard
instance_class: F1

# Añadimos esto para resolver el Warning y forzar un refresco de cuotas
automatic_scaling:
  min_instances: 0
  max_instances: 1
  target_cpu_utilization: 0.65
  entrypoint: node app.js
